version: '2'
services:
    activemq:
        build: .
        image: activemq
        container_name: activemq
        tty: true
        stdin_open: true
        ports:
            - "8161:8161"
            - "61616:61616"
